### ISSUE TITLE
Impossible

### ISSUE THREAD

**Issue by cetuuus** [Kiwidudev/WebOs#2]
Vous n'avez pas accès aux composants depuis le navigateur, donc ce n'est pas possible

**Comment by Kiwidudev** [comment]
> Vous n'avez pas accès aux composants depuis le navigateur, donc ce n'est pas possible

Salut Cetus, je ne crois pas que tu ai compris le but du projet. Le but et de créer une interface web qui retranscrit la bureautique d'un Os. Donc les seuls logiciels qui y seront présents seront faits mains, comme un éditeur de texte. En aucun cas nous aurons besoin des composants.
